"use client";
import {useEffect,useRef,useState,type ReactNode} from "react";
import catalog from "../services/eod/src/brontide_eod/research_metrics.json";
import {getResearchJson,clearResearchCache} from "../lib/research-data";
import {ResearchTrades,researchColumnWidth} from "./ResearchTrades";
import {sampleResearchRun,demoStorageKey} from "../lib/review-demo";
import {useBrowserStore} from "../lib/use-browser-store";
import {WATCH_KEY,updateWatchlist,validWatchlist,type WatchItem,type MarketContext} from "../lib/workspace-state";
import {initialResearchLayouts,validResearchLayouts,researchPresets,headlineDefaults,moveColumn,type ResearchLayout,type ResearchLayouts} from "../lib/research-layout";
import "./research-backtest.css";
import {LeanComparison} from "./LeanComparison";

type Metric=typeof catalog.metrics[number];
type Row=Record<string,unknown>&{symbol:string;setup_date:string;measurements?:Record<string,unknown>;conditions?:{condition:string;observed:unknown;operator:string;threshold:unknown;status:string;unit:string}[]};
type Analytics={scope:string;version:string;values:Record<string,number|null>;unavailable:Record<string,string>;distribution:{label:string;count:number}[];basis?:string;ordering?:string};
type Run={run_id:string;manifest:{strategy?:Record<string,unknown>;start:string;end:string;[key:string]:unknown};summary:Record<string,unknown>;execution?:Record<string,unknown>;analytics?:Analytics};
const contextColumns=[{...catalog.metrics[0],id:"run_start",label:"Start date",unit:"date",scope:"run",category:"Run context",definition:"First scored setup date in the saved run.",inputs:["manifest.start"],limitations:"Recorded run window"},{...catalog.metrics[0],id:"run_end",label:"End date",unit:"date",scope:"run",category:"Run context",definition:"Last scored setup date in the saved run.",inputs:["manifest.end"],limitations:"Recorded run window"}];
const byId=Object.fromEntries([...catalog.metrics,...contextColumns].map(m=>[m.id,m]));
const runMetrics=catalog.metrics.filter(m=>m.scope==="run");
const registryMetrics=[...runMetrics,...contextColumns];
const tradeMetrics=catalog.metrics.filter(m=>m.scope==="trade"&&m.id!=="symbol");
const valueOf=(row:Row,key:string)=>key.startsWith("setup.")?row.measurements?.[key.slice(6)]:row[key];
function format(value:unknown,unit="") {
  if(value===null||value===undefined)return "—";
  if(typeof value==="boolean")return value?"Yes":"No";
  if(typeof value!=="number")return typeof value==="object"?JSON.stringify(value):String(value);
  if(!Number.isFinite(value))return "—";
  if(unit==="fraction")return `${(value*100).toFixed(1)}%`;
  if(unit==="percent")return `${value>0?"+":""}${value.toFixed(2)}%`;
  if(unit==="R")return `${value>0?"+":""}${value.toFixed(2)}R`;
  if(unit==="USD")return `$${value.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
  return value.toLocaleString(undefined,{maximumFractionDigits:unit==="count"?0:2});
}
function saveJson(value:unknown,name:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url);}
function Dialog({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}) {
  const ref=useRef<HTMLDialogElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>{previous?.focus();};},[]);
  return <dialog ref={ref} className={`rb-dialog ${wide?"rb-wide":""}`} aria-label={title} onCancel={e=>{e.preventDefault();onClose();}}><header className="rb-dialog-header"><h2>{title}</h2><button onClick={onClose} aria-label={`Close ${title}`}>Close</button></header>{children}</dialog>;
}
function Help({metric}:{metric:Metric}) {return <details className="rb-help"><summary aria-label={`About ${metric.label}`}>?</summary><div><strong>{metric.label} · {metric.unit}</strong><p>{metric.definition}</p><p>{metric.limitations}</p><small>Inputs: {metric.inputs.join(", ")}</small></div></details>;}

// Explicitly synthetic demo adapter; local data is never accessed in demo mode.
async function demoRequest<T>(path:string,signal:AbortSignal):Promise<T>{
  signal.throwIfAborted();const u=new URL(path,"https://sample.invalid");const source=sampleResearchRun("backtest");
  const rows=source.rows.map((r,i)=>({...r,status:"Closed",trade_id:r.signal_id,entry:100,stop:98,target:120,exit:i?98:104,fees_per_share:0,hold_sessions:i?1:2,exit_reason:i?"Stop":"Maximum hold"})) as Row[];
  const values:Record<string,number|null>=Object.fromEntries(runMetrics.map(m=>[m.id,null]));
  Object.assign(values,{signals:2,entered:2,closed:2,winners:1,losers:1,breakeven:0,open:0,unresolved:0,not_entered:0,ambiguous_count:0,invalid_closed:0,total_r:1,expectancy_r:.5,median_r:.5,win_rate:.5,average_win_r:2,average_loss_r:-1,payoff_ratio:2,profit_factor_r:2,best_r:2,worst_r:-1,top_five_winners_r:2,winning_streak:1,losing_streak:1,closed_trade_drawdown_r:1,average_hold_sessions:1.5});
  const a:Analytics={version:catalog.version,scope:"whole run",values,unavailable:Object.fromEntries(runMetrics.filter(m=>values[m.id]===null).map(m=>[m.id,m.availability==="requires_portfolio"?m.limitations:"Not present in synthetic fixture"])),distribution:[],basis:"Synthetic layout fixture; not strategy evidence"};
  const run={...source,analytics:a};
  if(u.pathname.endsWith("/runs"))return {runs:[run]} as T;
  const symbol=(u.searchParams.get("symbol")??"").toUpperCase();const selected=rows.filter(r=>r.symbol.includes(symbol));
  if(u.pathname.endsWith("/analytics")){
    if(symbol){const v={...values};for(const k of Object.keys(v))v[k]=null;const outcomes=selected.map(r=>Number(r.outcome_r));Object.assign(v,{signals:selected.length,closed:selected.length,total_r:outcomes.reduce((x,y)=>x+y,0),expectancy_r:outcomes.length?outcomes.reduce((x,y)=>x+y,0)/outcomes.length:null,win_rate:outcomes.length?outcomes.filter(x=>x>0).length/outcomes.length:null});return {...a,values:v,scope:`Filtered cohort: ${symbol}`} as T;}return a as T;
  }
  if(u.pathname.includes("/trades/"))return {trade:rows.find(r=>String(r.trade_id)===u.pathname.split("/").at(-1))??rows[0]} as T;
  if(u.pathname.endsWith("/rows")){const sort=u.searchParams.get("sort")??"setup_date";const dir=u.searchParams.get("descending")==="true"?-1:1;selected.sort((a,b)=>{const x=valueOf(a,sort),y=valueOf(b,sort);if(x==null)return y==null?0:1;if(y==null)return -1;return (typeof x==="number"&&typeof y==="number"?x-y:String(x).localeCompare(String(y)))*dir;});const offset=Number(u.searchParams.get("offset")??0);return {rows:selected.slice(offset,offset+100),total:selected.length} as T;}
  return run as T;
}

export function ResearchBacktest({sample,onChart}:{sample:boolean;onChart:(context:MarketContext)=>void}){
  const request=sample?demoRequest:getResearchJson;
  const storage=useBrowserStore<ResearchLayouts>(demoStorageKey("brontide-research-layouts-v1",sample),initialResearchLayouts,validResearchLayouts);
  const watch=useBrowserStore<WatchItem[]>(demoStorageKey(WATCH_KEY,sample),[],validWatchlist);
  const [layout,setLayout]=useState<ResearchLayout>(initialResearchLayouts.layouts[0]);
  const [runs,setRuns]=useState<Run[]>([]),[selected,setSelected]=useState(""),[run,setRun]=useState<Run|null>(null);
  const [busy,setBusy]=useState(true),[error,setError]=useState(""),[retry,setRetry]=useState(0),[notice,setNotice]=useState("");
  const [editor,setEditor]=useState<"registry"|"trades"|null>(null),[search,setSearch]=useState(""),[metricsOpen,setMetricsOpen]=useState(false);
  const [compare,setCompare]=useState<string[]>([]),[comparison,setComparison]=useState(false);
  const [tradeOpen,setTradeOpen]=useState(false);
  const [registrySort,setRegistrySort]=useState("strategy"),[registryDesc,setRegistryDesc]=useState(false);
  useEffect(()=>{if(storage.ready)setLayout(storage.value.layouts.find(x=>x.id===storage.value.active)??storage.value.layouts[0]);},[storage.ready,storage.value]);
  useEffect(()=>{const abort=new AbortController();setBusy(true);setError("");request<{runs:Run[]}>("/v1/research/runs?kind=backtest&include_analytics=true",abort.signal).then(d=>{setRuns(d.runs);setSelected(old=>d.runs.some(r=>r.run_id===old)?old:d.runs[0]?.run_id??"");}).catch(e=>{if(!abort.signal.aborted)setError(e.message);}).finally(()=>{if(!abort.signal.aborted)setBusy(false);});return()=>abort.abort();},[sample,retry]);
  useEffect(()=>{setRun(null);if(!selected)return;const abort=new AbortController();request<Run>(`/v1/research/runs/${selected}?include_freshness=false`,abort.signal).then(d=>setRun({...d,analytics:runs.find(r=>r.run_id===selected)?.analytics})).catch(e=>{if(!abort.signal.aborted)setError(e.message);});return()=>abort.abort();},[selected,runs,sample]);
  const selectedRun=run??runs.find(r=>r.run_id===selected);
  const currentAnalytics=selectedRun?.analytics;
  const picked=runs.filter(r=>compare.includes(r.run_id));
  const compatible=new Set(picked.map(r=>JSON.stringify([r.manifest.data_fingerprint,r.manifest.universe_fingerprint,r.manifest.calendar_fingerprint,r.manifest.start,r.manifest.end,r.manifest.source,r.manifest.adjustment,r.manifest.execution_fingerprint]))).size<=1;
  const commit=(next:ResearchLayouts,message:string)=>{if(storage.save(next))setNotice(message);};
  const persist=()=>{if(!layout.name.trim()){setNotice("Give this layout a name.");return;}commit({...storage.value,active:layout.id,layouts:storage.value.layouts.some(x=>x.id===layout.id)?storage.value.layouts.map(x=>x.id===layout.id?layout:x):[...storage.value.layouts,layout]},"Layout saved on this device.");};
  const chart=(row:Row)=>{setTradeOpen(false);onChart({symbol:row.symbol,mode:sample?"sample":"local",adjustment:String(selectedRun?.manifest.adjustment??"all"),asOf:row.setup_date,signalId:String(row.signal_id??""),strategyId:String(row.strategy_id??"")});};
  const openTrades=(id:string)=>{setRun(null);setSelected(id);setTradeOpen(true);};
  const metricCell=(a:Analytics|undefined,key:string)=><span title={a?.unavailable[key]} className={key.includes("expectancy")&&Number(a?.values[key])>0?"rb-positive":""}>{format(a?.values[key],byId[key]?.unit)}</span>;
  const registryValue=(r:Run,k:string)=>k==="strategy"?String(r.manifest.strategy?.id):k==="run_start"?r.manifest.start:k==="run_end"?r.manifest.end:r.analytics?.values[k];
  const registryCell=(r:Run,k:string)=>k==="run_start"||k==="run_end"?<span>{String(registryValue(r,k))}</span>:metricCell(r.analytics,k);
  const fields=(kind:"registry"|"trades")=>layout[kind].filter(k=>byId[k]&&byId[k].scope===(kind==="registry"?"run":"trade")&&k!=="symbol");
  const registryRows=[...runs].sort((a,b)=>{const x=registryValue(a,registrySort);const y=registryValue(b,registrySort);if(x==null)return y==null?0:1;if(y==null)return -1;return (typeof x==="number"&&typeof y==="number"?x-y:String(x).localeCompare(String(y)))*(registryDesc?-1:1);});
  const layoutManagement=<div className="rb-toolbar rb-layout-management"><label>Layout name<input maxLength={80} value={layout.name} onChange={e=>setLayout({...layout,name:e.target.value})}/></label><button disabled={!storage.ready} onClick={()=>{const copy={...layout,id:crypto.randomUUID(),name:`${layout.name.slice(0,70)} copy`};commit({...storage.value,active:copy.id,layouts:[...storage.value.layouts,copy]},"Layout duplicated.");}}>Duplicate</button><button disabled={!storage.ready} onClick={()=>{const rest=storage.value.layouts.filter(x=>x.id!==layout.id);commit(rest.length?{version:1,active:rest[0].id,layouts:rest}:initialResearchLayouts,"Layout deleted; research data retained.");}}>Delete layout</button><label>Starting layout<select value="" onChange={e=>{const preset=researchPresets[e.target.value];if(preset)setLayout({...layout,...preset,widths:{}});}}><option value="">Apply a preset…</option>{Object.keys(researchPresets).map(k=><option key={k}>{k}</option>)}</select></label></div>;
  const columnEditor=editor&&<Dialog title="Customize columns" onClose={()=>setEditor(null)}><div className="rb-editor">{layoutManagement}<div className="rb-headline-editor">{layout.kpis.map((key,i)=><label key={i}>Headline {i+1}<select value={key} onChange={e=>{const next=[...layout.kpis];const other=next.indexOf(e.target.value);if(other>=0)next[other]=key;next[i]=e.target.value;setLayout({...layout,kpis:next});}}>{runMetrics.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label>)}</div><div className="rb-toolbar"><label>Table<select value={editor} onChange={e=>setEditor(e.target.value as "registry"|"trades")}><option value="registry">Run registry</option><option value="trades">Trade ledger</option></select></label><label>Find a metric<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search columns"/></label><button onClick={()=>setLayout({...layout,[editor]:researchPresets.Overview[editor],widths:{}})}>Reset columns</button></div><p>Identity and actions stay visible. Removing a column only changes this view.</p><div className="rb-column-order">{layout[editor].map((key,i)=><div key={key}><span>{byId[key]?.label??`${key} (unavailable)`}</span><button disabled={i===0} aria-label={`Move ${byId[key]?.label??key} left`} onClick={()=>setLayout({...layout,[editor]:moveColumn(layout[editor],i,-1)})}>←</button><button disabled={i===layout[editor].length-1} aria-label={`Move ${byId[key]?.label??key} right`} onClick={()=>setLayout({...layout,[editor]:moveColumn(layout[editor],i,1)})}>→</button><label>Width<input type="number" min={90} max={400} step={10} aria-label={`${byId[key]?.label??key} column width`} value={layout.widths[key]??researchColumnWidth(key)} onChange={e=>setLayout({...layout,widths:{...layout.widths,[key]:Math.max(90,Math.min(400,Number(e.target.value)||90))}})}/></label></div>)}</div>{[...new Set((editor==="registry"?registryMetrics:tradeMetrics).map(m=>m.category))].map(group=><section key={group}><h3>{group}</h3>{(editor==="registry"?registryMetrics:tradeMetrics).filter(m=>m.category===group&&`${m.label} ${m.definition}`.toLowerCase().includes(search.toLowerCase())).map(m=><div className="rb-column-choice" key={m.id}><label><input type="checkbox" checked={layout[editor].includes(m.id)} onChange={e=>setLayout({...layout,[editor]:e.target.checked?[...layout[editor],m.id]:layout[editor].filter(k=>k!==m.id)})}/>{m.label} <small>{m.unit}</small></label><Help metric={m}/>{m.availability==="requires_portfolio"&&<small>Requires portfolio model</small>}</div>)}</section>)}<button className="rb-primary" disabled={!storage.ready} onClick={persist}>Save layout</button><p role="status">{notice}</p></div></Dialog>;
  return <div className="rb-root">
    <header className="rb-command"><div><p className="rb-eyebrow">STRATEGY EVIDENCE</p><h2>Research backtests</h2><p>Compare the evidence. Inspect the trades. Keep the assumptions in view.</p></div><button onClick={()=>{clearResearchCache();setRetry(x=>x+1);}}>Refresh runs</button></header>
    <div className="rb-toolbar rb-viewbar"><label>Saved layout<select aria-label="Saved research layout" value={storage.value.active} disabled={!storage.ready} onChange={e=>commit({...storage.value,active:e.target.value},"Layout loaded.")}>{storage.value.layouts.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button onClick={()=>{setSearch("");setEditor("registry");}}>Layout & columns</button></div>
    {(notice||storage.error)&&<p role={storage.error?"alert":"status"}>{storage.error||notice}</p>}
    {busy&&<p className="rb-loading" role="status">{runs.length?"Updating saved research…":"Loading saved research…"}</p>}{error&&<p role="alert">{error} <button onClick={()=>setRetry(x=>x+1)}>Retry</button></p>}
    {!busy&&!error&&!runs.length&&<article className="rb-panel rb-empty"><h3>No saved research runs</h3><p>Completed offline research will appear here. Opening this page does not download data or start a job.</p></article>}
    {selectedRun&&<><section className="rb-hero"><div className="rb-verdict"><span className="rb-badge">{sample?"Synthetic example":"Current engine / Provisional evidence"}</span><h2>{String(selectedRun.manifest.strategy?.id??"Saved run")}</h2><p>{selectedRun.manifest.start} – {selectedRun.manifest.end}</p><small>{selectedRun.run_id.slice(0,12)} · {String(selectedRun.manifest.adjustment)} prices · independent trades</small></div><div className="rb-kpis">{layout.kpis.map((key,i)=><article key={i}><div className="rb-metric-title"><button onClick={()=>setMetricsOpen(true)}>{byId[key]?.label}</button></div><strong>{metricCell(currentAnalytics,key)}</strong><small>{currentAnalytics?.unavailable[key]??"Whole run · net trade outcomes"}</small></article>)}</div></section>
    <div className="rb-layout"><article className="rb-panel rb-registry"><header className="rb-panel-heading"><div><h3>Run registry</h3><p>{runs.length} saved {runs.length===1?"run":"runs"} · select a strategy to review its evidence</p></div><button disabled={picked.length<2} onClick={()=>setComparison(true)}>Compare selected ({picked.length})</button></header><div className="rb-table-wrap" tabIndex={0} role="region" aria-label="Research run table"><table><thead><tr><th><span className="rb-sr">Select</span></th><th aria-sort={registrySort==="strategy"?(registryDesc?"descending":"ascending"):"none"}><button onClick={()=>{setRegistrySort("strategy");setRegistryDesc(registrySort==="strategy"?!registryDesc:false);}}>Strategy</button></th>{fields("registry").map(key=><th key={key} style={{minWidth:layout.widths[key]??researchColumnWidth(key),width:layout.widths[key]??researchColumnWidth(key)}} aria-sort={registrySort===key?(registryDesc?"descending":"ascending"):"none"}><button onClick={()=>{setRegistrySort(key);setRegistryDesc(registrySort===key?!registryDesc:true);}}>{byId[key].label}</button></th>)}<th>Evidence</th></tr></thead><tbody>{registryRows.map(r=><tr key={r.run_id} className={r.run_id===selected?"rb-selected":""}><td><input type="checkbox" aria-label={`Compare ${String(r.manifest.strategy?.id)} ${r.run_id.slice(0,8)}`} checked={compare.includes(r.run_id)} onChange={e=>setCompare(e.target.checked?[...compare,r.run_id]:compare.filter(k=>k!==r.run_id))}/></td><th scope="row"><button className="rb-run-name" title={`${r.manifest.start} to ${r.manifest.end} / ${r.run_id.slice(0,8)}`} aria-pressed={r.run_id===selected} onClick={()=>setSelected(r.run_id)}>{String(r.manifest.strategy?.id)}</button></th>{fields("registry").map(key=><td key={key}>{registryCell(r,key)}</td>)}<td><button className="rb-text-action" onClick={()=>openTrades(r.run_id)}>View trades →</button></td></tr>)}</tbody></table></div></article>
    <aside className="rb-side"><article className="rb-panel"><p className="rb-eyebrow">SELECTED RUN</p><h3>{String(selectedRun.manifest.strategy?.id)}</h3><p>{selectedRun.manifest.start} – {selectedRun.manifest.end} · Current engine</p><h4>Conditions & execution</h4><dl><dt>EP volume expansion</dt><dd>{format(selectedRun.manifest.strategy?.ep_multiple,"ratio")}×</dd><dt>Setup RVOL below</dt><dd>{format(selectedRun.manifest.strategy?.setup_rvol,"ratio")}×</dd><dt>Setup window</dt><dd>{format(selectedRun.manifest.strategy?.min_age)}–{format(selectedRun.manifest.strategy?.max_age)} sessions</dd><dt>Target / maximum hold</dt><dd>{format(selectedRun.manifest.strategy?.target_r,"R")} / {format(selectedRun.manifest.strategy?.max_hold)} sessions</dd><dt>Entry</dt><dd>{String(selectedRun.manifest.strategy?.entry_policy??"See provenance")}</dd></dl>{run?.execution&&<p>{String(run.execution.same_bar_policy??run.execution.provenance??"")}</p>}<details><summary>Exact definition & provenance</summary><pre>{JSON.stringify({manifest:selectedRun.manifest,execution:run?.execution},null,2)}</pre></details><LeanComparison key={`${sample}-${selectedRun.run_id}`} runId={selectedRun.run_id} sample={sample} renderDialog={(children,onClose)=><Dialog title="Current engine & LEAN" onClose={onClose} wide>{children}</Dialog>}/></article><article className="rb-panel"><h3>Coverage & context</h3><dl>{["signals","closed","open","unresolved","not_entered","missing_symbols"].map(key=><div key={key}><dt>{byId[key].label}</dt><dd>{metricCell(currentAnalytics,key)}</dd></div>)}</dl><p>{String(selectedRun.manifest.eligibility??"Synthetic fixture; no historical eligibility claim.")}</p><button onClick={()=>setMetricsOpen(true)}>Explore all metrics</button>{sample?<button onClick={()=>saveJson(sampleResearchRun("backtest"),"sample-research-ledger.json")}>Download sample ledger</button>:<a href={`/v1/research/runs/${selectedRun.run_id}/export`} download>Download complete run / ledger</a>}</article></aside></div>
    <p className="rb-footnote">Whole-run summaries describe independent trades, not a capital-constrained portfolio. Historical eligibility and corporate actions require separate review.</p></>}
    {metricsOpen&&<Dialog title="Metric catalog & evidence" onClose={()=>setMetricsOpen(false)} wide><div className="rb-editor"><p>{catalog.version} · Whole-run analytics · Units and missing inputs are explicit.</p><button onClick={()=>saveJson({catalog,analytics:currentAnalytics},"research-metric-catalog.json")}>Export catalog & analytics</button><div className="rb-catalog-grid">{runMetrics.map(m=><article className="rb-panel" key={m.id}><h3>{m.label} <Help metric={m}/></h3><strong>{metricCell(currentAnalytics,m.id)}</strong><p>{currentAnalytics?.unavailable[m.id]??m.definition}</p></article>)}</div><h3>Closed-trade outcome distribution</h3>{currentAnalytics?.distribution.map(b=><div className="rb-distribution" key={b.label}><span>{b.label}</span><meter min={0} max={Math.max(1,Number(currentAnalytics.values.closed))} value={b.count}/><strong>{b.count}</strong></div>)}<p>{currentAnalytics?.ordering}</p></div></Dialog>}
    {comparison&&<Dialog title="Compare saved runs" onClose={()=>setComparison(false)} wide><div className="rb-editor"><p role={compatible?"status":"alert"}>{compatible?"Selected runs share recorded data, periods, and execution fingerprints. Strategy definitions may differ.":"These runs use different data, periods, or execution assumptions. This is not a controlled strategy comparison."}</p><div className="rb-table-wrap"><table><thead><tr><th>Metric</th>{picked.map(r=><th key={r.run_id}>{String(r.manifest.strategy?.id)}<small>{r.run_id.slice(0,8)} / Current engine</small></th>)}</tr></thead><tbody>{fields("registry").map(k=><tr key={k}><th>{byId[k].label}</th>{picked.map(r=><td key={r.run_id}>{registryCell(r,k)}</td>)}</tr>)}</tbody></table></div></div></Dialog>}
    {tradeOpen&&selectedRun&&<ResearchTrades key={selectedRun.run_id} runId={selectedRun.run_id} strategy={String(selectedRun.manifest.strategy?.id)} layout={layout} request={request} onClose={()=>setTradeOpen(false)} onColumns={()=>{setSearch("");setEditor("trades");}} onChart={chart} onWatch={r=>watch.save(updateWatchlist(watch.value,r.symbol,"add"))} inWatchlist={r=>watch.value.some(w=>w.symbol===r.symbol)} watchReady={watch.ready} watchError={watch.error??""} onRefresh={clearResearchCache}/>}
    {columnEditor}
  </div>;
}
