-- Captured schema shape from the existing optional Catalyst integration; no market data.
create table if not exists public.catalyst_reports (
  id uuid default gen_random_uuid() not null,
  report_type text not null,
  trading_date_checked date not null,
  generated_at_sgt timestamp with time zone not null,
  coverage_window text,
  market_session_focus text,
  output_version text default 'Catalyst_Table_v2'::text not null,
  market_summary text,
  themes_summary text,
  best_focus text,
  table_1_tickers text[] default '{}'::text[] not null,
  table_2_tickers text[] default '{}'::text[] not null,
  table_3_tickers text[] default '{}'::text[] not null,
  raw_report_text text,
  created_at timestamp with time zone default now() not null,
  constraint catalyst_reports_output_version_check CHECK ((output_version = 'Catalyst_Table_v2'::text)),
  constraint catalyst_reports_pkey PRIMARY KEY (id),
  constraint catalyst_reports_report_type_check CHECK ((report_type = ANY (ARRAY['Premarket Catalyst Brief'::text, 'After-Market Catalyst Brief'::text, 'Weekend Catalyst Summary'::text]))),
  constraint catalyst_reports_report_type_trading_date_checked_generated_key UNIQUE (report_type, trading_date_checked, generated_at_sgt)
);
alter table public.catalyst_reports enable row level security;
create table if not exists public.catalyst_rows (
  id bigint generated by default as identity not null,
  report_id uuid not null,
  table_number smallint not null,
  row_order integer not null,
  ticker text not null,
  catalyst_event_date text not null,
  catalyst_quality_direction text not null,
  primary_catalyst_category text not null,
  catalyst_tags text not null,
  catalyst_summary text not null,
  sector text not null,
  theme text not null,
  direct_sympathy_sector_move text not null,
  sympathy_related_tickers text not null,
  catalyst_release_session text not null,
  reaction_date text not null,
  move_already_done text not null,
  volume_liquidity_confirmation text not null,
  freshness_catalyst_age text not null,
  source_confidence text not null,
  primary_source_evidence text not null,
  trade_read text not null,
  risk_invalidator text not null,
  action_priority text not null,
  trading_date_checked date not null,
  created_at timestamp with time zone default now() not null,
  constraint catalyst_rows_action_priority_check CHECK ((action_priority = ANY (ARRAY['High-Conviction Watch'::text, 'Starter Watch'::text, 'Watch'::text, 'Avoid Chase'::text, 'Avoid'::text, 'Short Watch'::text, 'Avoid Short'::text]))),
  constraint catalyst_rows_catalyst_quality_direction_check CHECK ((catalyst_quality_direction = ANY (ARRAY['A+ Bullish'::text, 'A Bullish'::text, 'B Bullish'::text, 'N / Neutral'::text, 'A+ Bearish'::text, 'A Bearish'::text, 'B Bearish'::text, 'Sympathy / Continuation'::text, 'No Fresh Catalyst'::text]))),
  constraint catalyst_rows_catalyst_release_session_check CHECK ((catalyst_release_session = ANY (ARRAY['Premarket'::text, 'Regular Market Hours'::text, 'After Close'::text, 'Overnight'::text, 'Weekend / Holiday'::text, 'Needs Verification'::text]))),
  constraint catalyst_rows_direct_sympathy_sector_move_check CHECK ((direct_sympathy_sector_move = ANY (ARRAY['Direct'::text, 'Sympathy'::text, 'Sector Move'::text, 'Mixed'::text, 'None'::text]))),
  constraint catalyst_rows_pkey PRIMARY KEY (id),
  constraint catalyst_rows_primary_catalyst_category_check CHECK ((primary_catalyst_category = ANY (ARRAY['Earnings'::text, 'Guidance / Business Update'::text, 'Clinical Data'::text, 'FDA / Regulatory'::text, 'M&A / Strategic Transaction'::text, 'Contract / Orders'::text, 'Analyst Action'::text, 'Capital Markets / Financing'::text, 'Corporate Action'::text, 'Legal / Accounting'::text, 'Product / Commercial'::text, 'Macro / Policy'::text, 'Sector / Sympathy'::text, 'Scheduled Event'::text, 'No Fresh Catalyst'::text]))),
  constraint catalyst_rows_report_id_fkey FOREIGN KEY (report_id) REFERENCES catalyst_reports(id) ON DELETE CASCADE,
  constraint catalyst_rows_report_id_table_number_row_order_key UNIQUE (report_id, table_number, row_order),
  constraint catalyst_rows_row_order_check CHECK ((row_order > 0)),
  constraint catalyst_rows_sector_check CHECK ((sector = ANY (ARRAY['Technology'::text, 'Healthcare'::text, 'Consumer Discretionary'::text, 'Consumer Staples'::text, 'Industrials'::text, 'Energy'::text, 'Financials'::text, 'Communication Services'::text, 'Materials'::text, 'Utilities'::text, 'Real Estate'::text, 'Crypto / Digital Assets'::text, 'ETF / Index'::text, 'Other'::text]))),
  constraint catalyst_rows_source_confidence_check CHECK ((source_confidence = ANY (ARRAY['High'::text, 'Medium'::text, 'Low'::text]))),
  constraint catalyst_rows_table_grade_check CHECK ((((table_number = 1) AND (catalyst_quality_direction = ANY (ARRAY['A+ Bullish'::text, 'A Bullish'::text]))) OR ((table_number = 2) AND (catalyst_quality_direction = ANY (ARRAY['A+ Bearish'::text, 'A Bearish'::text]))) OR (table_number = 3))),
  constraint catalyst_rows_table_number_check CHECK ((table_number = ANY (ARRAY[1, 2, 3])))
);
alter table public.catalyst_rows enable row level security;

-- Preserve existing policies; bootstrap the optional feed for new installations.
do $$ begin
  if not exists(select 1 from pg_policies where tablename='catalyst_reports' and cmd='SELECT') then
    create policy "Authenticated users can read catalyst reports" on public.catalyst_reports for select to authenticated using(true);
  end if;
  if not exists(select 1 from pg_policies where tablename='catalyst_rows' and cmd='SELECT') then
    create policy "Authenticated users can read catalyst rows" on public.catalyst_rows for select to authenticated using(true);
  end if;
end $$;
grant select on public.catalyst_reports,public.catalyst_rows to authenticated;
grant all on public.catalyst_reports,public.catalyst_rows to service_role;
grant usage,select on sequence public.catalyst_rows_id_seq to service_role;

alter table public.catalyst_reports
  add column if not exists report_key text,
  add column if not exists source text,
  add column if not exists coverage_start date,
  add column if not exists coverage_end date,
  add column if not exists published_at timestamptz,
  add column if not exists scheduled_for timestamptz,
  add column if not exists revision integer,
  add column if not exists result_count integer;
alter table public.catalyst_reports add column if not exists last_received_at timestamptz;
create unique index if not exists catalyst_report_identity on public.catalyst_reports(source,report_type,report_key) where report_key is not null;
alter table public.catalyst_reports drop constraint if exists catalyst_reports_report_type_trading_date_checked_generated_key;
create unique index if not exists catalyst_legacy_report_identity on public.catalyst_reports(report_type,trading_date_checked,generated_at_sgt) where report_key is null;
-- No legacy timestamps, types or completeness are guessed or rewritten.
create table public.catalyst_report_revisions (
  report_id uuid not null references public.catalyst_reports(id),
  revision integer not null check(revision>0),
  received_at timestamptz not null default now(),
  payload jsonb not null,
  primary key(report_id,revision)
);
alter table public.catalyst_report_revisions enable row level security;
revoke all on public.catalyst_report_revisions from anon,authenticated;
grant select,insert on public.catalyst_report_revisions to service_role;

create table public.catalyst_report_schedules (
  report_type text primary key check(report_type in ('Premarket','Postmarket','Weekend Summary')),
  timezone text not null,
  weekdays integer[] not null check(cardinality(weekdays)>0 and weekdays <@ array[1,2,3,4,5,6,7]),
  local_time time not null,
  grace_minutes integer check(grace_minutes between 0 and 1440),
  effective_from timestamptz not null,
  evidence text not null check(length(trim(evidence))>0)
);
alter table public.catalyst_report_schedules enable row level security;
create policy "Read catalyst schedule metadata" on public.catalyst_report_schedules for select to authenticated using(true);
grant select on public.catalyst_report_schedules to authenticated;
grant all on public.catalyst_report_schedules to service_role;
-- Intentionally no default schedules: producer configuration has not been observed.

create table public.catalyst_delivery_events (
  id bigint generated always as identity primary key,
  report_type text check(report_type in ('Premarket','Postmarket','Weekend Summary')),
  report_id uuid references public.catalyst_reports(id),
  stage text not null check(stage in ('scheduler','generation','ingestion','publication')),
  status text not null check(status in ('started','succeeded','failed')),
  observed_at timestamptz not null default now(),
  scheduled_for timestamptz,
  summary text check(summary in ('Report accepted','Duplicate delivery','Correction accepted','Invalid report payload','Revision conflict','Generation failed','Scheduler run failed','Scheduler run completed','Run started'))
);
alter table public.catalyst_delivery_events enable row level security;
create policy "Read catalyst delivery metadata" on public.catalyst_delivery_events for select to authenticated using(true);
grant select on public.catalyst_delivery_events to authenticated;
grant select,insert on public.catalyst_delivery_events to service_role;
grant usage,select on sequence public.catalyst_delivery_events_id_seq to service_role;
create view public.catalyst_delivery_status with (security_invoker=true) as
select distinct on(report_type,stage) report_type,stage,status,observed_at,scheduled_for,summary
from public.catalyst_delivery_events order by report_type,stage,observed_at desc,id desc;
grant select on public.catalyst_delivery_status to authenticated;

create or replace function public.ingest_catalyst_report(payload jsonb)
returns jsonb language plpgsql security invoker set search_path='' as $$
declare
  kind text; legacy_kind text; rid uuid; existing public.catalyst_reports;
  revision_number integer; expected_revision integer; item jsonb; row_value public.catalyst_rows;
  stored_payload jsonb; failure_summary text := 'Invalid report payload';
  report_date date; start_date date; end_date date; published timestamptz; generated timestamptz; scheduled timestamptz;
begin
  -- This inner transaction rolls back all report changes on any validation/constraint failure.
  begin
    kind:=payload->>'report_type';
    legacy_kind:=case kind when 'Premarket' then 'Premarket Catalyst Brief' when 'Postmarket' then 'After-Market Catalyst Brief' when 'Weekend Summary' then 'Weekend Catalyst Summary' end;
    if legacy_kind is null or jsonb_typeof(payload)<>'object'
      or jsonb_typeof(payload->'report_key') is distinct from 'string'
      or jsonb_typeof(payload->'source') is distinct from 'string'
      or coalesce(length(trim(payload->>'report_key')),0) not between 1 and 200
      or coalesce(length(trim(payload->>'source')),0) not between 1 and 200
      or payload->>'source' <> trim(payload->>'source')
      or payload->>'report_key' <> trim(payload->>'report_key')
      or jsonb_typeof(payload->'raw_report_text') is distinct from 'string'
      or coalesce(length(trim(payload->>'raw_report_text')),0) not between 1 and 2000000
      or coalesce(jsonb_typeof(payload->'rows'),'null')<>'array'
      or coalesce(payload->>'output_version','')<>'Catalyst_Table_v2'
      or coalesce(payload->>'revision','') !~ '^[1-9][0-9]*$'
      or coalesce(payload->>'expected_revision','') !~ '^[0-9]+$'
      or coalesce(payload->>'report_date','') !~ '^\d{4}-\d{2}-\d{2}$'
      or coalesce(payload->>'coverage_start','') !~ '^\d{4}-\d{2}-\d{2}$'
      or coalesce(payload->>'coverage_end','') !~ '^\d{4}-\d{2}-\d{2}$'
      or coalesce(payload->>'published_at','') !~ 'T.*(Z|[+-]\d{2}:\d{2})$'
      or coalesce(payload->>'generated_at','') !~ 'T.*(Z|[+-]\d{2}:\d{2})$'
    then raise exception 'Invalid report'; end if;
    if exists(select 1 from jsonb_each(payload) e where e.key in ('raw_report_text','coverage_window','market_session_focus','market_summary','themes_summary','best_focus') and jsonb_typeof(e.value) not in ('string','null')) then raise exception 'Invalid metadata'; end if;
    report_date:=(payload->>'report_date')::date;
    start_date:=(payload->>'coverage_start')::date; end_date:=(payload->>'coverage_end')::date;
    published:=(payload->>'published_at')::timestamptz; generated:=(payload->>'generated_at')::timestamptz;
    if start_date>end_date or generated>published or published>now()+interval '5 minutes' then raise exception 'Invalid dates'; end if;
    if payload->>'scheduled_for' is not null then
      if payload->>'scheduled_for' !~ 'T.*(Z|[+-]\d{2}:\d{2})$' then raise exception 'Invalid run time'; end if;
      scheduled:=(payload->>'scheduled_for')::timestamptz;
    end if;
    revision_number:=(payload->>'revision')::integer; expected_revision:=(payload->>'expected_revision')::integer;
    -- Serialize concurrent first deliveries and corrections of the same identity.
    perform pg_advisory_xact_lock(hashtextextended(concat_ws('|',kind,payload->>'source',payload->>'report_key'),0));
    select * into existing from public.catalyst_reports
      where report_type=legacy_kind and source=payload->>'source' and report_key=payload->>'report_key' for update;
    if existing.id is not null then
      select r.payload into stored_payload from public.catalyst_report_revisions r where r.report_id=existing.id and r.revision=revision_number;
      if stored_payload=payload then
        insert into public.catalyst_delivery_events(report_type,report_id,stage,status,scheduled_for,summary)
          values(kind,existing.id,'ingestion','succeeded',scheduled,'Duplicate delivery');
        return jsonb_build_object('status','duplicate','report_id',existing.id,'revision',revision_number);
      end if;
      if expected_revision<>existing.revision or revision_number<>existing.revision+1
        or report_date<>existing.trading_date_checked or published<existing.published_at then
        failure_summary:='Revision conflict';raise exception 'Conflict';
      end if;
      rid:=existing.id;
    elsif revision_number<>1 or expected_revision<>0 then
      failure_summary:='Revision conflict';raise exception 'Conflict';
    else rid:=gen_random_uuid();
    end if;
    if jsonb_array_length(payload->'rows')>3000 then raise exception 'Too many rows'; end if;
    insert into public.catalyst_reports(id,report_type,trading_date_checked,generated_at_sgt,coverage_window,output_version,market_summary,themes_summary,best_focus,report_key,source,coverage_start,coverage_end,published_at,scheduled_for,revision,result_count)
      values(rid,legacy_kind,report_date,generated,payload->>'coverage_window','Catalyst_Table_v2',payload->>'market_summary',payload->>'themes_summary',payload->>'best_focus',payload->>'report_key',payload->>'source',start_date,end_date,published,scheduled,revision_number,(select count(*) from jsonb_array_elements(payload->'rows') r where r->>'table_number'='3'))
      on conflict(id) do update set generated_at_sgt=excluded.generated_at_sgt,coverage_window=excluded.coverage_window,market_summary=excluded.market_summary,themes_summary=excluded.themes_summary,best_focus=excluded.best_focus,coverage_start=excluded.coverage_start,coverage_end=excluded.coverage_end,published_at=excluded.published_at,scheduled_for=excluded.scheduled_for,revision=excluded.revision,result_count=excluded.result_count;
    -- Earlier immutable payloads retain every row and metadata field from prior revisions.
    delete from public.catalyst_rows where report_id=rid;
    for item in select value from jsonb_array_elements(payload->'rows') loop
      if jsonb_typeof(item)<>'object' or item ? 'report_id' or item ? 'id' or item ? 'created_at'
        or coalesce(item->>'trading_date_checked','')<>report_date::text
        or coalesce(length(trim(item->>'ticker')),0)=0 then raise exception 'Invalid row'; end if;
      row_value:=jsonb_populate_record(null::public.catalyst_rows,item);
      insert into public.catalyst_rows(report_id,table_number,row_order,ticker,catalyst_event_date,catalyst_quality_direction,primary_catalyst_category,catalyst_tags,catalyst_summary,sector,theme,direct_sympathy_sector_move,sympathy_related_tickers,catalyst_release_session,reaction_date,move_already_done,volume_liquidity_confirmation,freshness_catalyst_age,source_confidence,primary_source_evidence,trade_read,risk_invalidator,action_priority,trading_date_checked)
      values(rid,row_value.table_number,row_value.row_order,row_value.ticker,row_value.catalyst_event_date,row_value.catalyst_quality_direction,row_value.primary_catalyst_category,row_value.catalyst_tags,row_value.catalyst_summary,row_value.sector,row_value.theme,row_value.direct_sympathy_sector_move,row_value.sympathy_related_tickers,row_value.catalyst_release_session,row_value.reaction_date,row_value.move_already_done,row_value.volume_liquidity_confirmation,row_value.freshness_catalyst_age,row_value.source_confidence,row_value.primary_source_evidence,row_value.trade_read,row_value.risk_invalidator,row_value.action_priority,row_value.trading_date_checked);
    end loop;
    if exists(select 1 from public.catalyst_rows r where r.report_id=rid and r.table_number in (1,2) and not exists(select 1 from public.catalyst_rows c where c.report_id=rid and c.table_number=3 and c.ticker=r.ticker)) then raise exception 'Table 3 incomplete'; end if;
    update public.catalyst_reports set
      last_received_at=now(),
      raw_report_text=payload->>'raw_report_text',market_session_focus=payload->>'market_session_focus',
      table_1_tickers=array(select ticker from public.catalyst_rows where report_id=rid and table_number=1 order by row_order),
      table_2_tickers=array(select ticker from public.catalyst_rows where report_id=rid and table_number=2 order by row_order),
      table_3_tickers=array(select ticker from public.catalyst_rows where report_id=rid and table_number=3 order by row_order)
    where id=rid;
    insert into public.catalyst_report_revisions(report_id,revision,payload) values(rid,revision_number,payload);
    insert into public.catalyst_delivery_events(report_type,report_id,stage,status,scheduled_for,summary)
      values(kind,rid,'ingestion','succeeded',scheduled,case when revision_number=1 then 'Report accepted' else 'Correction accepted' end),
            (kind,rid,'publication','succeeded',scheduled,'Report accepted');
    return jsonb_build_object('status',case when revision_number=1 then 'published' else 'corrected' end,'report_id',rid,'revision',revision_number);
  exception when others then
    insert into public.catalyst_delivery_events(report_type,stage,status,scheduled_for,summary)
      values(case when kind in ('Premarket','Postmarket','Weekend Summary') then kind end,'ingestion','failed',scheduled,failure_summary);
    return jsonb_build_object('status','rejected','error',failure_summary);
  end;
end $$;
revoke all on function public.ingest_catalyst_report(jsonb) from public,anon,authenticated;
grant execute on function public.ingest_catalyst_report(jsonb) to service_role;

-- Reuse the canonical Table 3 feed and keep its invoker security boundary.
create or replace view public.catalyst_dashboard_rows with (security_invoker=true) as
select cr.id as report_id,cr.report_type,cr.generated_at_sgt,cr.market_summary,cr.themes_summary,cr.best_focus,cr.output_version,
r.table_number,r.row_order,r.ticker,r.catalyst_event_date,r.catalyst_quality_direction,r.primary_catalyst_category,r.catalyst_tags,r.catalyst_summary,r.sector,r.theme,r.direct_sympathy_sector_move,r.sympathy_related_tickers,r.catalyst_release_session,r.reaction_date,r.move_already_done,r.volume_liquidity_confirmation,r.freshness_catalyst_age,r.source_confidence,r.primary_source_evidence,r.trade_read,r.risk_invalidator,r.action_priority,r.trading_date_checked
from public.catalyst_reports cr join public.catalyst_rows r on r.report_id=cr.id where r.table_number=3;
grant select on public.catalyst_dashboard_rows to authenticated;
